# Generated by Django 5.2.7 on 2025-11-29 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("slack", "Slack"),
                            ("jira", "Jira"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("service_event", models.CharField(max_length=100)),
                ("external_id", models.CharField(max_length=255)),
                ("target_url", models.TextField()),
                ("secret", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["user", "service_type"], name="integration_user_id_f237fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["is_active"], name="integration_is_acti_b01307_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["integration", "service_event"],
                name="webhooks_integra_e377ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["is_active"], name="webhooks_is_acti_7ab6f5_idx"
            ),
        ),
    ]
