# Generated by Django 5.2.7 on 2025-11-23 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("workspace_created", "Workspace Created"),
                            ("workspace_updated", "Workspace Updated"),
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                            ("member_role_changed", "Member Role Changed"),
                            ("project_created", "Project Created"),
                            ("project_updated", "Project Updated"),
                            ("project_deleted", "Project Deleted"),
                            ("invitation_sent", "Invitation Sent"),
                            ("invitation_accepted", "Invitation Accepted"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the activity",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data about the activity",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Activity",
                "verbose_name_plural": "Workspace Activities",
                "db_table": "workspace_activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-timestamp"],
                        name="workspace_a_workspa_283e20_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="workspace_a_user_id_fb06f1_idx",
                    ),
                    models.Index(
                        fields=["action"], name="workspace_a_action_4cc8d5_idx"
                    ),
                ],
            },
        ),
    ]
