# Generated by Django 5.2.7 on 2025-11-19 14:46

import django.core.serializers.json
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_hash",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("access_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI Cache Entry",
                "verbose_name_plural": "AI Cache Entries",
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        help_text="task, meeting, analytics, etc.", max_length=50
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Template with {{variable}} placeholders."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list,
                        help_text="List of required variable names, e.g., ['task_description', 'user_name']",
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        choices=[("flash", "Gemini Flash"), ("pro", "Gemini Pro")],
                        default="flash",
                        max_length=50,
                    ),
                ),
                ("default_max_tokens", models.IntegerField(default=1024)),
                ("temperature", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI Prompt Template",
                "verbose_name_plural": "AI Prompt Templates",
            },
        ),
        migrations.CreateModel(
            name="AIRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("daily_limit", models.IntegerField(default=100)),
                ("tokens_limit_day", models.IntegerField(default=400000)),
                ("requests_today", models.IntegerField(default=0)),
                ("tokens_today", models.IntegerField(default=0)),
                ("last_reset", models.DateTimeField(default=django.utils.timezone.now)),
                ("minute_limit", models.IntegerField(default=60)),
                ("requests_this_minute", models.IntegerField(default=0)),
                (
                    "minute_reset_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "feature_cost_today",
                    models.IntegerField(
                        default=0,
                        help_text="Aggregated cost of high-value features like STT/Structured tasks.",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Rate Limit",
                "verbose_name_plural": "AI Rate Limits",
            },
        ),
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., task_ai, meeting_ai, analytics_ai",
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(db_index=True, default="gemini", max_length=50),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="e.g., gemini-1.5-flash, gemini-1.5-pro",
                        max_length=50,
                    ),
                ),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Seconds taken for the API call",
                        null=True,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Truncated request payload sent to the AI provider.",
                        null=True,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Truncated response payload received from the AI provider.",
                        null=True,
                    ),
                ),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "db_table": "ai_usages",
                "ordering": ["-created_at"],
            },
        ),
    ]
