# Generated by Django 5.2.7 on 2025-11-19 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_features", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprompttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="airatelimit",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_rate_limit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="user",
            field=models.ForeignKey(
                help_text="The user who initiated the AI feature use.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="workspace",
            field=models.ForeignKey(
                help_text="The workspace associated with this usage event.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_usages",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiprompttemplate",
            unique_together={("name", "category")},
        ),
        migrations.AddIndex(
            model_name="aiusage",
            index=models.Index(
                fields=["user", "created_at"], name="ai_usages_user_id_6ddfba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusage",
            index=models.Index(
                fields=["feature_type", "success"], name="ai_usages_feature_40c43c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusage",
            index=models.Index(
                fields=["provider", "model_used"], name="ai_usages_provide_4030f0_idx"
            ),
        ),
    ]
