# Generated by Django 5.2.7 on 2025-11-19 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for project",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If True, project is visible to all workspace members",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict, help_text="Project configuration settings"
                    ),
                ),
                ("task_count", models.IntegerField(default=0)),
                ("completed_task_count", models.IntegerField(default=0)),
                ("member_count", models.IntegerField(default=1)),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Project completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("archived", "Archived"),
                            ("restored", "Restored"),
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                            ("task_created", "Task Created"),
                            ("task_completed", "Task Completed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Human-readable activity description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional activity data"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Activity",
                "verbose_name_plural": "Project Activities",
                "db_table": "project_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code for label",
                        max_length=7,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Label",
                "verbose_name_plural": "Project Labels",
                "db_table": "project_labels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        db_index=True,
                        default="member",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_project_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "db_table": "project_members",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "template_data",
                    models.JSONField(
                        default=dict,
                        help_text="Template configuration including default tasks, labels, etc.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If True, template is available to all users",
                    ),
                ),
                ("use_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, template is private to workspace",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_templates",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Template",
                "verbose_name_plural": "Project Templates",
                "db_table": "project_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "status"], name="projects_workspa_658984_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "owner"], name="projects_workspa_760234_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="projects_owner_i_c299b3_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="projects_status_6303d7_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["priority"], name="projects_priorit_bdc554_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["slug"], name="projects_slug_25ccba_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("workspace", "slug")},
        ),
        migrations.AddIndex(
            model_name="projectactivity",
            index=models.Index(
                fields=["project", "-created_at"], name="project_act_project_ed9341_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectactivity",
            index=models.Index(
                fields=["user", "-created_at"], name="project_act_user_id_2e1961_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectactivity",
            index=models.Index(fields=["action"], name="project_act_action_458aed_idx"),
        ),
        migrations.AddIndex(
            model_name="projectlabel",
            index=models.Index(
                fields=["project"], name="project_lab_project_9860b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectlabel",
            index=models.Index(fields=["name"], name="project_lab_name_06a67e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="projectlabel",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "user"], name="project_mem_project_9e0a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["project", "role"], name="project_mem_project_0d0b7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(fields=["user"], name="project_mem_user_id_f59cbb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "user")},
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["workspace"], name="project_tem_workspa_898cd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["created_by"], name="project_tem_created_7721af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["is_public"], name="project_tem_is_publ_a55b00_idx"
            ),
        ),
    ]
