# Generated by Django 5.2.7 on 2025-11-19 14:46

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Task title/summary", max_length=500),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Rich text description of the task"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="todo",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Task priority level",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Task due date and time",
                        null=True,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated hours to complete",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Array of tag strings for categorization",
                        size=None,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Position for manual ordering",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible metadata. Used for: checklist",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent task for subtask hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "file_url",
                    models.URLField(help_text="URL to the stored file", max_length=500),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Attachment",
                "verbose_name_plural": "Task Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(help_text="Comment content (supports markdown)"),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users mentioned in this comment",
                        related_name="mentioned_in_task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment for threaded replies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tasks.taskcomment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who wrote this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[("blocks", "Blocks"), ("blocked_by", "Blocked By")],
                        default="blocks",
                        help_text="Type of dependency relationship",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on",
                    models.ForeignKey(
                        help_text="The task this depends on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="tasks.task",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="The dependent task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Dependency",
                "verbose_name_plural": "Task Dependencies",
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Task title template (supports variables like {project_name})",
                        max_length=500,
                    ),
                ),
                (
                    "description_template",
                    models.TextField(blank=True, help_text="Task description template"),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "default_estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "default_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Template category (e.g., Bug Fix, Feature, Research)",
                        max_length=100,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this template is available to all users",
                    ),
                ),
                (
                    "subtask_templates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of subtask templates to create",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        blank=True, default=list, help_text="Default checklist items"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Template",
                "verbose_name_plural": "Task Templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, help_text="Hours worked", max_digits=6
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date when work was performed",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this time entry is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged this time",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Entry",
                "verbose_name_plural": "Time Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="tasks_task_project_b78682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="tasks_task_assigne_b3b2bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date"], name="tasks_task_due_dat_bce847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority", "status"], name="tasks_task_priorit_685c61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["parent_task"], name="tasks_task_parent__a05e1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(
                fields=["task", "created_at"], name="tasks_taska_task_id_3aa34c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskattachment",
            index=models.Index(
                fields=["uploaded_by"], name="tasks_taska_uploade_08f373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["task"], name="tasks_taskc_task_id_8332b2_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(fields=["user"], name="tasks_taskc_user_id_192c4f_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["parent_comment"], name="tasks_taskc_parent__ec71a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(
                fields=["task", "dependency_type"],
                name="tasks_taskd_task_id_b27623_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskdependency",
            unique_together={("task", "depends_on", "dependency_type")},
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(
                fields=["category", "is_public"], name="tasks_taskt_categor_77e15c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasktemplate",
            index=models.Index(
                fields=["created_by"], name="tasks_taskt_created_35ef6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["task", "date"], name="tasks_timee_task_id_2c4852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["user", "date"], name="tasks_timee_user_id_c91571_idx"
            ),
        ),
    ]
