from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import NotificationViewSet, NotificationPreferenceView, UnreadCountView

app_name = 'notifications'

router = DefaultRouter()
# Base path for notifications (GET /list/, POST /:id/mark_as_read/, etc.)
router.register('', NotificationViewSet, basename='notification')

urlpatterns = [
    # Includes all routes generated by the router
    path('', include(router.urls)),
    
    # Custom routes
    path('preferences/', NotificationPreferenceView.as_view(), name='preferences'),
    path('unread-count/', UnreadCountView.as_view(), name='unread-count'),
]